; ── Embedded target ────────────────────────────────────────────────────────────
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200

; ; ── Native unit-test runner ────────────────────────────────────────────────────
; [env:native]
; platform = native
; test_framework = unity
; lib_ignore =
;     SimpleGPIO
;     SimplePWM
;     SimpleSerialBT
;     SimpleI2C
;     SimpleUART
;     SimpleLCD
;     SimpleRGB
;     SimpleADC
;     SimpleTimer
;     AS5600
;     TCS34725
;     Ultrasonic
;     Joystick
;     LineF
;     Stepper
;     Servo_Stepper
;     HBridge
;     Buzzer
;     Keyboard
;     Viscometer
;     I2C_Emebedded_C
;     QuadratureEncoder
;     PID_CAYETANO
;     SimplePID
;     Filter
; build_flags =
;     -lm
; test_filter = test_Matrix