[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200


[env:native]
platform = native
framework =
test_framework = unity
lib_deps =
    unity
lib_ignore =
    SimpleGPIO
    SimplePWM
    SimpleSerialBT
    SimpleI2C
    SimpleUART
    SimpleLCD
    SimpleRGB
    SimpleADC
    SimpleTimer
    AS5600
    TCS34725
    Ultrasonic
    Joystick
    LineF
    Stepper
    Servo_Stepper
    HBridge
    Buzzer
    Keyboard
    Viscometer
    I2C_Emebedded_C
    QuadratureEncoder
    PID_CAYETANO
    SimplePID
    Filter
build_src_flags =
    -I test/test_Matrix

[env:test]
platform = native
test_framework = unity
lib_ignore =
    SimpleGPIO
    SimplePWM
    SimpleSerialBT
    SimpleI2C
    SimpleUART
    SimpleLCD
    SimpleRGB
    SimpleADC
    SimpleTimer
    AS5600
    TCS34725
    Ultrasonic
    Joystick
    LineF
    Stepper
    Servo_Stepper
    HBridge
    Buzzer
    Keyboard
    Viscometer
    I2C_Emebedded_C
    QuadratureEncoder
    PID_CAYETANO
    SimplePID
    Filter
 
